### ISSUE TITLE
Function error: missing_scope

### ISSUE THREAD

**Issue by ma91n** [future-architect/gbilling-plot#11]
# Environment

* Running with CloudFunction

# Version

latest(2019.08.23)

# Logs

I guess slack access token permission.
Token may be needed to file:write permission.

```
2019-08-23T08:51:21.930995072Z graphGcpBilling 7ti7kj8gjtbt Function execution took 3916 ms, finished with status: 'error' D  graphGcpBilling 7ti7kj8gjtbt
2019-08-23T08:51:22.950Z graphGcpBilling 7ti7kj8gjtbt Function error: missing_scope

goroutine 10 [running]:
runtime/debug.Stack(0xb4f300, 0xc0002c8b28, 0x94)
	/go/src/runtime/debug/stack.go:24 +0xa7
main.executeFunction(0xd21080, 0xc0002ae2a0, 0xc0000f6800)
	/tmp/sgb/staging/srv/worker.go:193 +0x7fb
net/http.HandlerFunc.ServeHTTP(0xc7df98, 0xd21080, 0xc0002ae2a0, 0xc0000f6800)
	/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0x1489e80, 0xd21080, 0xc0002ae2a0, 0xc0000f6800)
	/go/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0002a52b0, 0xd21080, 0xc0002ae2a0, 0xc0000f6800)
	/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000264d20, 0xd21c00, 0xc0002a8c80)
	/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/go/src/net/http/server.go:2851 +0x2f5
 E  graphGcpBilling 7ti7kj8gjtbt
```

**Comment by ma91n** [comment]
Slack access token permission is lack. 
You need `file:write` permission.
Update README.

**Comment by ma91n** [comment]
done #18
